apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api
spec:
  replicas: 4
  selector:
    matchLabels:
      app: product-api
  template:
    metadata:
      labels:
        app: product-api
    spec:
      containers:
      - name: product-api
        image: kamaloncode/productapi:1.0
        ports:
        - containerPort: 80
        env:
        - name: DB_SERVER
          valueFrom:
            configMapKeyRef:
              name: product-api-config
              key: DB_SERVER
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: product-api-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: product-api-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: product-api-secret
              key: DB_PASSWORD
